import type { NextPage } from 'next';
import { signIn, signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
  const { data } = useSession();

  if (!data)
    return (
      <div className="flex grow flex-col items-center justify-center">
        <div className="text-2xl font-bold">Please log in below</div>
        <div className="p-4" />
        <button
          onClick={() => signIn('google')}
          className="flex items-center gap-2 rounded bg-gray-200 px-4 py-2 text-2xl text-black"
        >
          <span>Sign in with Google</span>
          {/* <FaTwitch /> */}
        </button>
      </div>
    );

  return (
    <>
      <Head>
        <title>PU - Track your workouts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Signed in!</div>
      <button
        onClick={() => signOut()}
        className="flex items-center gap-2 rounded bg-gray-200 px-4 py-2 text-2xl text-black"
      >
        <span>Sign Out</span>
        {/* <FaTwitch /> */}
      </button>
      <div className="flex flex-col">
        <div className="flex w-full items-center justify-between bg-gray-800 py-4 px-8 shadow">
          <h1 className="flex items-center gap-2 text-2xl font-bold">
            {data.user?.image && (
              <img
                src={data.user?.image}
                alt={`${data.user?.name} profile pic`}
                className="w-16 rounded-full"
              />
            )}
            {data.user?.name}
          </h1>
        </div>
      </div>
    </>
  );
};

export default Home;
