import type { NextPage } from 'next';
import { signIn, signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import { FaSignOutAlt, FaGoogle } from 'react-icons/fa';
import SignedInLayout from '../components/SignedInLayout';

import Workouts from '../components/Workouts';

const NavButtons = () => {
  return (
    <div className="flex gap-2">
      <button
        onClick={() => signOut()}
        className="flex gap-2 rounded bg-gray-200 p-4 font-bold text-gray-800 hover:bg-gray-100"
      >
        Logout <FaSignOutAlt size={24} />
      </button>
    </div>
  );
};

const Home: NextPage = () => {
  const { data } = useSession();

  if (!data)
    return (
      <div className="flex grow flex-col items-center justify-center">
        <div className="text-2xl font-bold">Please log in below</div>
        <div className="p-4" />
        <button
          onClick={() => signIn('google')}
          className="flex items-center gap-2 rounded bg-gray-200 px-4 py-2 text-2xl text-black"
        >
          <span>Sign in with Google</span>
          <FaGoogle />
        </button>
      </div>
    );

  return (
    <>
      <Head>
        <title>PU - Track your workouts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignedInLayout user={data.user}>
        <Workouts />
      </SignedInLayout>
    </>
  );
};

export default Home;
